{"name": "test_time_series_daily", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following failure was found in \"test_time_series_daily\" (test_time_series_daily.Test_TimeSeriesDaily):\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/home/san/PycharmProjects/pythonTestProject/Lib/Assertions.py\", line 5, in assert_equal\n    self.soft_assert(self.assertEqual, actual, expected,\n  File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_time_series_daily.py\", line 22, in test_time_series_daily\n    self.assertion.assert_equal(response.status_code, 202,\"Expected status code is 200 but found \"+str(response.status_code))\n  File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 200 != 202 : Expected status code is 200 but found 200\n\n-+ [1/1] +-", "trace": "self = <test_time_series_daily.Test_TimeSeriesDaily testMethod=test_time_series_daily>\n\n    def test_time_series_daily(self):\n        self.logger.info(\"test started\")\n        url = self.base_url+\"function=TIME_SERIES_DAILY&symbol=\"+self.symbol+\"&apikey=\"+self.apiKey\n        self.logger.info(\"url : \" + url)\n        response = requests.get(url)\n        response_json = response.json()\n    \n        self.logger.info(\"response : \"+ response.text)\n    \n        # verify status code\n        self.assertion.assert_equal(response.status_code, 202,\"Expected status code is 200 but found \"+str(response.status_code))\n    \n        # header validation\n        self.soft_assert(self.assertEqual, response.headers.get('Content-Type'), \"application/json\",\n                         msg=\"Expected Content-Type is application/json but found \"+ response.headers.get('Content-Type'))\n    \n        # symbol validation\n        self.soft_assert(self.assertEqual, response_json['Meta Data']['2. Symbol'] , \"IBM\",\n                         msg=\"Expected symbol is IBM but found \"+ response_json['Meta Data']['2. Symbol'])\n    \n        # response json schema validation\n        path = Path(__file__).parent.parent/\"Config/schema.json\"\n        data = open(path).read()\n        content = json.loads(data)\n        try:\n            validate(instance=response_json, schema=content)\n        except jsonschema.exceptions.ValidationError as ve:\n            self.logger.info(\"error log\")\n            self.soft_assert(self.assertTrue, False,\n                             msg=ve)\n        self.logger.info(\"test ended\")\n>       self.assert_all()\n\nTests/test_time_series_daily.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../.local/lib/python3.8/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following failure was found in \"test_time_series_daily\" (test_time_series_daily.Test_TimeSeriesDaily):\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/home/san/PycharmProjects/pythonTestProject/Lib/Assertions.py\", line 5, in assert_equal\nE       self.soft_assert(self.assertEqual, actual, expected,\nE     File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_time_series_daily.py\", line 22, in test_time_series_daily\nE       self.assertion.assert_equal(response.status_code, 202,\"Expected status code is 200 but found \"+str(response.status_code))\nE     File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\nE       raise self.failureException(msg)\nE   AssertionError: 200 != 202 : Expected status code is 200 but found 200\nE   \nE   -+ [1/1] +-"}, "attachments": [{"name": "log", "source": "ab51276f-0e0c-4c62-9800-4343f3e6e9de-attachment.txt", "type": "text/plain"}], "start": 1611644793887, "stop": 1611644795416, "uuid": "db486cca-e496-4253-a396-222c0a3fce5d", "historyId": "f72e9e8460fdc3c3945b05f1e3d0d240", "testCaseId": "b0b28eb7e1d9b7a4ee52a06ade1fc03d", "fullName": "Tests.test_time_series_daily.Test_TimeSeriesDaily#test_time_series_daily", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_time_series_daily"}, {"name": "subSuite", "value": "Test_TimeSeriesDaily"}, {"name": "host", "value": "san-ThinkPad-T480"}, {"name": "thread", "value": "267330-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_time_series_daily"}]}