{"name": "test_time_series_daily", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"test_time_series_daily\" (test_time_series_daily.Test_TimeSeriesDaily):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"test_time_series_daily\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_time_series_daily.py\", line 22, in test_time_series_daily\n    self.soft_assert(self.assertEqual,response.status_code,201, msg = \"Expected status code is 200 but found \"+str(response.status_code))\n  File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 200 != 201 : Expected status code is 200 but found 200\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"test_time_series_daily\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_time_series_daily.py\", line 25, in test_time_series_daily\n    self.soft_assert(self.assertEqual,response.headers.get('Content-Type'), \"applicationn/json\",  msg=\"Expected Content-Type is application/json but found \"+ response.headers.get('Content-Type'))\n  File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 1292, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.8/unittest/case.py\", line 753, in fail\n    raise self.failureException(msg)\nAssertionError: 'application/json' != 'applicationn/json'\n- application/json\n+ applicationn/json\n?            +\n : Expected Content-Type is application/json but found application/json\n\n-+ [2/2] +-", "trace": "self = <test_time_series_daily.Test_TimeSeriesDaily testMethod=test_time_series_daily>\n\n    def test_time_series_daily(self):\n        self.logger.info(\"test started\")\n        url = self.base_url+\"function=TIME_SERIES_DAILY&symbol=\"+self.symbol+\"&apikey=\"+self.apiKey\n        print(url)\n        response = requests.get(url)\n    \n        self.logger.info(\"response : \"+ response.text)\n    \n        # verify status code\n        self.soft_assert(self.assertEqual,response.status_code,201, msg = \"Expected status code is 200 but found \"+str(response.status_code))\n    \n        # header validation\n        self.soft_assert(self.assertEqual,response.headers.get('Content-Type'), \"applicationn/json\",  msg=\"Expected Content-Type is application/json but found \"+ response.headers.get('Content-Type'))\n    \n        # response body validations\n        # assert\n        self.logger.info(\"test ended\")\n>       print(self.assert_all())\n\nTests/test_time_series_daily.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../.local/lib/python3.8/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"test_time_series_daily\" (test_time_series_daily.Test_TimeSeriesDaily):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"test_time_series_daily\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_time_series_daily.py\", line 22, in test_time_series_daily\nE       self.soft_assert(self.assertEqual,response.status_code,201, msg = \"Expected status code is 200 but found \"+str(response.status_code))\nE     File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\nE       raise self.failureException(msg)\nE   AssertionError: 200 != 201 : Expected status code is 200 but found 200\nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"test_time_series_daily\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_time_series_daily.py\", line 25, in test_time_series_daily\nE       self.soft_assert(self.assertEqual,response.headers.get('Content-Type'), \"applicationn/json\",  msg=\"Expected Content-Type is application/json but found \"+ response.headers.get('Content-Type'))\nE     File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 1292, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 753, in fail\nE       raise self.failureException(msg)\nE   AssertionError: 'application/json' != 'applicationn/json'\nE   - application/json\nE   + applicationn/json\nE   ?            +\nE    : Expected Content-Type is application/json but found application/json\nE   \nE   -+ [2/2] +-"}, "attachments": [{"name": "log", "source": "17c10b73-13e3-4cf5-82ef-b995e9769c11-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "960b2d9a-b4b7-4426-b510-192f5e402ba5-attachment.txt", "type": "text/plain"}], "start": 1611589097073, "stop": 1611589098482, "uuid": "d9a22228-e082-46af-b3ab-e8409ae7e004", "historyId": "f72e9e8460fdc3c3945b05f1e3d0d240", "testCaseId": "b0b28eb7e1d9b7a4ee52a06ade1fc03d", "fullName": "Tests.test_time_series_daily.Test_TimeSeriesDaily#test_time_series_daily", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_time_series_daily"}, {"name": "subSuite", "value": "Test_TimeSeriesDaily"}, {"name": "host", "value": "san-ThinkPad-T480"}, {"name": "thread", "value": "215082-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_time_series_daily"}]}