{
  "uid" : "673cb90e3bafa44a",
  "name" : "test_company_overview",
  "fullName" : "Tests.test_company_overview.Test_CompanyOverview#test_company_overview",
  "historyId" : "5ccb5911223bd14f7dd4b1c66a495591",
  "time" : {
    "start" : 1611645613588,
    "stop" : 1611645614824,
    "duration" : 1236
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following failure was found in \"test_company_overview\" (test_company_overview.Test_CompanyOverview):\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/home/san/PycharmProjects/pythonTestProject/Lib/Assertions.py\", line 5, in assert_equal\n    self.soft_assert(self.assertEqual, actual, expected,\n  File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_company_overview.py\", line 24, in test_company_overview\n    self.assertion.assert_equal(response.status_code, 201 ,\"Expected status code is 200 but found \"+str(response.status_code))\n  File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 200 != 201 : Expected status code is 200 but found 200\n\n-+ [1/1] +-",
  "statusTrace" : "self = <test_company_overview.Test_CompanyOverview testMethod=test_company_overview>\n\n    def test_company_overview(self):\n        self.logger.info(\"test started\")\n        url = self.base_url+\"function=OVERVIEW&symbol=\"+self.symbol+\"&apikey=\"+self.apiKey\n        self.logger.info(\"url : \" + url)\n        response = requests.get(url)\n        response_json = response.json()\n    \n        self.logger.info(\"response : \"+ response.text)\n    \n        # verify status code\n        self.assertion.assert_equal(response.status_code, 201 ,\"Expected status code is 200 but found \"+str(response.status_code))\n    \n        # header validation\n        self.assertion.assert_equal(response.headers.get('Content-Type'), \"application/json\",\n                         \"Expected Content-Type is application/json but found \"+ response.headers.get('Content-Type'))\n    \n        # symbol validation\n        self.assertion.assert_equal(response_json['Symbol'] , \"IBM\",\n                         \"Expected symbol is IBM but found \"+ response_json['Symbol'])\n    \n        # response json schema validation\n        path = Path(__file__).parent.parent/\"Config/companyOverview.json\"\n        data = open(path).read()\n        content = json.loads(data)\n        try:\n            validate(instance=response_json, schema=content)\n        except jsonschema.exceptions.ValidationError as ve:\n            self.logger.info(\"error log\")\n            self.soft_assert(self.assertTrue, False,\n                             msg=ve)\n        self.logger.info(\"test ended\")\n>       self.assert_all()\n\nTests/test_company_overview.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../.local/lib/python3.8/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following failure was found in \"test_company_overview\" (test_company_overview.Test_CompanyOverview):\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/home/san/PycharmProjects/pythonTestProject/Lib/Assertions.py\", line 5, in assert_equal\nE       self.soft_assert(self.assertEqual, actual, expected,\nE     File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_company_overview.py\", line 24, in test_company_overview\nE       self.assertion.assert_equal(response.status_code, 201 ,\"Expected status code is 200 but found \"+str(response.status_code))\nE     File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\nE       raise self.failureException(msg)\nE   AssertionError: 200 != 201 : Expected status code is 200 but found 200\nE   \nE   -+ [1/1] +-",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "unittest_setUpClass_fixture_Test_CompanyOverview",
    "time" : {
      "start" : 1611645613587,
      "stop" : 1611645613587,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following failure was found in \"test_company_overview\" (test_company_overview.Test_CompanyOverview):\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/home/san/PycharmProjects/pythonTestProject/Lib/Assertions.py\", line 5, in assert_equal\n    self.soft_assert(self.assertEqual, actual, expected,\n  File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_company_overview.py\", line 24, in test_company_overview\n    self.assertion.assert_equal(response.status_code, 201 ,\"Expected status code is 200 but found \"+str(response.status_code))\n  File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 200 != 201 : Expected status code is 200 but found 200\n\n-+ [1/1] +-",
    "statusTrace" : "self = <test_company_overview.Test_CompanyOverview testMethod=test_company_overview>\n\n    def test_company_overview(self):\n        self.logger.info(\"test started\")\n        url = self.base_url+\"function=OVERVIEW&symbol=\"+self.symbol+\"&apikey=\"+self.apiKey\n        self.logger.info(\"url : \" + url)\n        response = requests.get(url)\n        response_json = response.json()\n    \n        self.logger.info(\"response : \"+ response.text)\n    \n        # verify status code\n        self.assertion.assert_equal(response.status_code, 201 ,\"Expected status code is 200 but found \"+str(response.status_code))\n    \n        # header validation\n        self.assertion.assert_equal(response.headers.get('Content-Type'), \"application/json\",\n                         \"Expected Content-Type is application/json but found \"+ response.headers.get('Content-Type'))\n    \n        # symbol validation\n        self.assertion.assert_equal(response_json['Symbol'] , \"IBM\",\n                         \"Expected symbol is IBM but found \"+ response_json['Symbol'])\n    \n        # response json schema validation\n        path = Path(__file__).parent.parent/\"Config/companyOverview.json\"\n        data = open(path).read()\n        content = json.loads(data)\n        try:\n            validate(instance=response_json, schema=content)\n        except jsonschema.exceptions.ValidationError as ve:\n            self.logger.info(\"error log\")\n            self.soft_assert(self.assertTrue, False,\n                             msg=ve)\n        self.logger.info(\"test ended\")\n>       self.assert_all()\n\nTests/test_company_overview.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../.local/lib/python3.8/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following failure was found in \"test_company_overview\" (test_company_overview.Test_CompanyOverview):\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/home/san/PycharmProjects/pythonTestProject/Lib/Assertions.py\", line 5, in assert_equal\nE       self.soft_assert(self.assertEqual, actual, expected,\nE     File \"/home/san/PycharmProjects/pythonTestProject/Tests/test_company_overview.py\", line 24, in test_company_overview\nE       self.assertion.assert_equal(response.status_code, 201 ,\"Expected status code is 200 but found \"+str(response.status_code))\nE     File \"/home/san/.local/lib/python3.8/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 912, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/usr/lib/python3.8/unittest/case.py\", line 905, in _baseAssertEqual\nE       raise self.failureException(msg)\nE   AssertionError: 200 != 201 : Expected status code is 200 but found 200\nE   \nE   -+ [1/1] +-",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "ed0583ec6452f956",
      "name" : "log",
      "source" : "ed0583ec6452f956.txt",
      "type" : "text/plain",
      "size" : 4258
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "unittest_setUpClass_fixture_Test_CompanyOverview::0",
    "time" : {
      "start" : 1611645619214,
      "stop" : 1611645619214,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "Tests"
  }, {
    "name" : "suite",
    "value" : "test_company_overview"
  }, {
    "name" : "subSuite",
    "value" : "Test_CompanyOverview"
  }, {
    "name" : "host",
    "value" : "san-ThinkPad-T480"
  }, {
    "name" : "thread",
    "value" : "268176-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "Tests.test_company_overview"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "673cb90e3bafa44a.json",
  "parameterValues" : [ ]
}